# Phase 1: Use npm to build and generate static content
FROM node:alpine as builder_phase
WORKDIR '/app'
COPY package.json .
RUN npm install
COPY . .
RUN npm run build

# Phase 2: Copy all the static content generated by the npm build in phase 1 and host this on nginx
FROM nginx
COPY --from=builder_phase /app/build /usr/share/nginx/html
# There is no need to specify a RUN stage explicitly. This is because the base nginx image already contains this instruction out of the box
